# Generated by Django 4.2.2 on 2023-06-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tittle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle_name', models.CharField(max_length=30, verbose_name='Tittle Name')),
            ],
        ),
    ]
