# Generated by Django 4.2.2 on 2023-06-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.CharField(max_length=30, verbose_name='content1')),
                ('content2', models.CharField(max_length=30, verbose_name='content2')),
                ('content3', models.CharField(max_length=30, verbose_name='content3')),
                ('content4', models.CharField(max_length=30, verbose_name='content4')),
                ('menu_icon', models.ImageField(upload_to='images', verbose_name='Menu Icon')),
            ],
        ),
    ]
