# Generated by Django 4.2.2 on 2023-06-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images', verbose_name='Header logo')),
                ('name1', models.CharField(max_length=30, verbose_name='name1')),
                ('name2', models.CharField(max_length=30, verbose_name='name2')),
                ('image', models.ImageField(upload_to='images', verbose_name='Header image')),
                ('button_name1', models.CharField(max_length=30, verbose_name='Button name 1')),
                ('button_name2', models.CharField(max_length=30, verbose_name='Button name 2')),
            ],
        ),
    ]
