# Generated by Django 4.2.2 on 2023-06-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('image', models.ImageField(upload_to='images', verbose_name='Protein image')),
                ('price', models.IntegerField(verbose_name='Protein price')),
                ('protein_type', models.CharField(max_length=30, verbose_name='Protein Type')),
                ('button_name', models.CharField(max_length=30, verbose_name='button name')),
            ],
        ),
    ]
