# Generated by Django 4.2.2 on 2023-06-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_protein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='name',
        ),
    ]
