# Generated by Django 4.2.2 on 2023-06-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Growyhing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_name', models.CharField(max_length=30, verbose_name='Button Name')),
                ('image', models.ImageField(upload_to='images', verbose_name='Image')),
            ],
        ),
    ]
