# Generated by Django 4.2.2 on 2023-06-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_growyhing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_img', models.ImageField(upload_to='images', verbose_name='Protein Image')),
                ('carusel_img', models.ImageField(upload_to='images', verbose_name='Carusel Image')),
                ('carusel_name', models.CharField(max_length=30, verbose_name='Carusel Name')),
                ('text', models.TextField(verbose_name='Text')),
            ],
        ),
    ]
