# Generated by Django 4.2.2 on 2023-06-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=60, verbose_name='Phone Number')),
                ('location', models.CharField(max_length=60, verbose_name='Location')),
                ('gmail', models.EmailField(max_length=254, verbose_name='Gmail')),
            ],
        ),
    ]
