# Generated by Django 4.2.2 on 2023-06-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_supported'),
    ]

    operations = [
        migrations.CreateModel(
            name='Futter_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=30, verbose_name='Name1')),
                ('name2', models.CharField(max_length=30, verbose_name='Name2')),
            ],
        ),
    ]
